---
- name: Download Nginx Source
  get_url: url=http://nginx.org/download/nginx-1.8.0.tar.gz dest=/usr/local/src/nginx-1.8.0.tar.gz

- name: Unpack Nginx Source
  command: tar -C /usr/local/src -xf /usr/local/src/nginx-1.8.0.tar.gz creates=/usr/local/src/nginx-1.8.0

- name: Install Dependencies
  yum: name={{ item }} state=installed
  with_items:
    - gcc
    - pcre-devel
    - zlib-devel

- name: Compile Nginx
  shell: ./configure && make && make install chdir=/usr/local/src/nginx-1.8.0 creates=/usr/local/nginx/sbin/nginx

- name: Init Script
  copy: src=etc/init.d/nginx dest=/etc/init.d/nginx mode=0775

- name: Nginx Configuration
  copy: src={{ item }} dest=/usr/local/nginx/conf/
  with_items:
    - nginx.conf
    - varnish.conf

- name: Start Nginx
  service: name=nginx state=started
