---
- name: Install Dependencies
  yum: name={{ item }} state=present
  with_items:
    - git
    - go

- name: Install Cacheproxy
  shell: go get github.com/shawnsi/cacheproxy && go install github.com/shawnsi/cacheproxy
  environment:
    GOPATH: /tmp

- name: Run Cacheproxy
  shell: /tmp/bin/cacheproxy -proxy 80 -replicas 1 &
  async: 1
  poll: 0

- name: Add Serf Peers to Cache Ring
  script: peers.sh
